### ISSUE TITLE
convert_deps_to_pip() got an unexpected keyword argument 'project'

### ISSUE THREAD

**Issue by DaanMarchal** [kurthaegeman/pre-commit-hooks-safety-pipenv#10]
```
check pipfile lock for insecure packages.................................Failed
- hook id: pipenv-safety-check
- exit code: 1

Traceback (most recent call last):
  File "/home/daan/.cache/pre-commit/repo73edatl3/py_env-python3.11/bin/safety_check", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/daan/.cache/pre-commit/repo73edatl3/py_env-python3.11/lib/python3.11/site-packages/src/safety_check.py", line 98, in main
    vulnerabilities = process_lockdata(pipfile_lock, args=args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daan/.cache/pre-commit/repo73edatl3/py_env-python3.11/lib/python3.11/site-packages/src/safety_check.py", line 52, in process_lockdata
    pip_deps = pipenv.utils.dependencies.convert_deps_to_pip(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: convert_deps_to_pip() got an unexpected keyword argument 'project'
```
 
 `10:28 $ pipenv --version
pipenv, version 2023.9.8
`

**Comment by kurthaegeman** [comment]
Solved! Thanks for your report!
